@Worknet.API_HostAddress = https://localhost:7047


GET {{Worknet.API_HostAddress}}/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRlMTRiZmU4LTFlZjctNGJlMC1hYmU1LTYxYWEzODMxYmRmMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJPTEVLU0FORFIiLCJleHAiOjE3NDkwNDQ4MzMsImlzcyI6IldvcmtuZXRBcHAiLCJhdWQiOiJXb3JrbmV0VXNlcnMifQ.oin0HOFMuvZDNDzkcmpSoWSXfsmnQFGxj3iKTWXjnYo


POST {{Worknet.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "UserEmail": "test4@example.com",
  "Password": "SecurePassword123!@"
}

###
POST {{Worknet.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "UserEmail": "test4@example.com",
  "Password": "SecurePassword123!@",
  "UserName": "Userok4"
}

###

POST {{Worknet.API_HostAddress}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlRFU1Q0QEVYQU1QTEUuQ09NIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlVTRVJPSzQiLCJleHAiOjE3NDgxMzM4ODUsImlzcyI6IldvcmtuZXRBcHAiLCJhdWQiOiJXb3JrbmV0VXNlcnMifQ.-HanaUqEn-dVFVcGoVIzOdnlOCy86HelhWCAuFXXark
###

POST {{Worknet.API_HostAddress}}/api/auth/logout

###

POST {{Worknet.API_HostAddress}}/api/auth/logout

###

POST {{Worknet.API_HostAddress}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlRFU1Q0QEVYQU1QTEUuQ09NIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlVTRVJPSzQiLCJleHAiOjE3NDg0ODY5MDksImlzcyI6IldvcmtuZXRBcHAiLCJhdWQiOiJXb3JrbmV0VXNlcnMifQ.rgqGg4zMcW0Unzto31BE1zWuG8EUhPtm10114VwWE0E

###
POST {{Worknet.API_HostAddress}}/api/profile/upload-file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

GET {{Worknet.API_HostAddress}}/api/profile

###
